language: clojure

lein: lein
jdk:
  - oraclejdk8

branches:
  only:
    - master

env:
  - CASSANDRA_VERSION=310

before_install:
  - sudo echo "deb http://www.apache.org/dist/cassandra/debian ${CASSANDRA_VERSION}x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - sudo echo "deb-src http://www.apache.org/dist/cassandra/debian ${CASSANDRA_VERSION}x main" | sudo tee -a /etc/apt/sources.list
  - sudo rm -rf ~/.gnupg
  - curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
  - sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-key A278B781FE4B2BDA
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y cassandra --force-yes
  - sudo rm -rf /var/lib/cassandra/*
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /etc/cassandra/cassandra-env.sh"
  - sudo service cassandra start
